import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Player } from "@remotion/player";
import MyComp from "../lib/remotion/Composition";
import { useState } from "react";
const Home: NextPage = () => {
  const [textValue, setTextValue] = useState("Hello World!");
  const [textInput, setTextInput] = useState("Hello World!");
  return (
    <div className={styles.container}>
      <Head>
        <title>Remotion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.videoContainer}>
          <Player
            component={MyComp}
            inputProps={{ text: textValue }}
            durationInFrames={240}
            compositionWidth={1920}
            compositionHeight={1080}
            fps={30}
            style={{
              width: 640,
              height: 360,
            }}
            controls
          />
        </div>
        <div>
          <input
            className={styles.inputBox}
            type="text"
            value={textInput}
            onChange={(e) => setTextInput(e.target.value)}
          />
          <button
            className={styles.button}
            onClick={() => {
              setTextValue(textInput);
            }}
          >
            Change Text
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
